export const EMAIL = "pralphv321@gmail.com"
export const GITHUB_PORTFOLIO = "https://github.com/pralphv/portfolio"
export const GITHUB_PAGE = "https://github.com/pralphv"
export const GITHUB_COLOR_SYSTEM_BUILDER = "https://github.com/pralphv/stripe_color_system_builder"
export const GITHUB_PETANGLE = "https://github.com/pralphv/petangle"
export const GITHUB_SITEMAP_GENERATOR = "https://github.com/pralphv/sitemap_generator"
export const LINKEDIN = "https://www.linkedin.com/in/ralph-vincent-o-perez-16b378122/"
